// Customizer const
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSE_MENU';
export const WINDOW_WIDTH = 'WINDOW-WIDTH';
export const SWITCH_LANGUAGE = 'SWITCH-LANGUAGE';

//Contact Module const
export const FETCH_START = 'fetch_start';
export const FETCH_SUCCESS = 'fetch_success';
export const FETCH_ERROR = 'fetch_error';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const ON_SHOW_LOADER = 'ON_SHOW_LOADER';
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER';

export const GET_CITY = 'GET_CITY';
export const GET_DISTRICT = 'GET_DISTRICT';

//Auth const
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNIN_GOOGLE_USER = 'SIGNIN_GOOGLE_USER';
export const SIGNIN_GOOGLE_USER_SUCCESS = 'SIGNIN_GOOGLE_USER_SUCCESS';
export const SIGNIN_FACEBOOK_USER = 'SIGNIN_FACEBOOK_USER';
export const SIGNIN_FACEBOOK_USER_SUCCESS = 'SIGNIN_FACEBOOK_USER_SUCCESS';
export const SIGNIN_TWITTER_USER = 'SIGNIN_TWITTER_USER';
export const SIGNIN_TWITTER_USER_SUCCESS = 'SIGNIN_TWITTER_USER_SUCCESS';
export const SIGNIN_GITHUB_USER = 'SIGNIN_GITHUB_USER';
export const SIGNIN_GITHUB_USER_SUCCESS = 'signin_github_user_success';
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const SET_USER_STT = 'SET_USER_STT';
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS';
export const INIT_URL = 'INIT_URL';
export const USER_DATA = 'user_data';
export const USER_TOKEN_SET = 'user_token_set';
export const GET_APP_INFO = 'get_app_info';

export const ACCOUNT_CHANGE_STT = 'ACCOUNT_CHANGE_STT';
export const ACCOUNT_CHANGE_STT_SUCCESS = 'ACCOUNT_CHANGE_STT_SUCCESS';
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
export const GET_ACCOUNT = 'GET_ACCOUNT';
export const GET_ACCOUNT_SUCCESS = 'GET_ACCOUNT_SUCCESS';
export const CHANGE_ACCOUNT_PASSWORD = 'CHANGE_ACCOUNT_PASSWORD';
export const CHANGE_ACCOUNT_PASSWORD_SUCCESS = 'CHANGE_ACCOUNT_PASSWORD_SUCCESS';
export const COMMON_GET_MENU = "C_G_M";
export const COMMON_GET_MENU_SUCCESS = "C_G_M_S";

export const GET_STICKY = 'GET_STICKY';
export const NOTES_UPDATE = 'NOTES_UPDATE';
export const FETCH_ALL_NOTES_SUCCESS = 'FETCH_ALL_NOTES_SUCCESS';
export const UPDATE_ALL_NOTES_SUCCESS = 'UPDATE_ALL_NOTES_SUCCESS';

export const ROLE_SUPPER_ADMIN = 'sadmin';
export const ROLE_ADMIN = 'Admin';
export const ROLE_SALE = 'sale';
export const ROLE_DOCTOR = 'doctor';
export const ROLE_SUPPORT = 'support';
export const ROLE_STAFF = 'staff';
export const ROLE_LEADER = 'leader';
export const ROLE_MARKETER = 'marketer';

//User page
export const GET_USER = 'GET_USER';
export const GET_USER_FAIL = 'GET_USER_FAIL';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const PROFILE_CHANGE_PASSWORD = 'PROFILE_CHANGE_PASSWORD';
export const PROFILE_CHANGE_PASSWORD_SUCCESS = 'PROFILE_CHANGE_PASSWORD_SUCCESS';

export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const GET_PRODUCT_DETAIL_SUCCESS = 'GET_PRODUCT_DETAIL_SUCCESS';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const CHANGE_STT_PRODUCT = 'CHANGE_STT_PRODUCT';
export const SET_P_STATE = 'SET_P_STATE';


export const PRODUCT_CAT_CREATE = 'PRODUCT/CREATE_CAT';
export const PRODUCT_CAT_CREATE_SUCCESS = 'PRODUCT/CREATE_CAT_SUCCESS';
export const PRODUCT_CAT_UPDATE = 'PRODUCT/UPDATE_CAT';
export const PRODUCT_CAT_UPDATE_SUCCESS = 'PRODUCT/UPDATE_CAT_SUCCESS';
export const PRODUCT_CAT_DEL_SUCCESS = 'PRODUCT/DEL_CAT_SUCCESS';
export const PRODUCT_CAT_DEL = 'PRODUCT/DEL_CAT';
export const PRODUCT_CAT_GET_LIST = 'PRODUCT/GET_LIST_CAT';
export const PRODUCT_CAT_GET_LIST_SUCCESS = 'PRODUCT/GET_LIST_CAT_SUCCESS';


export const GET_PO = 'GET_PO';
export const GET_PO_DETAIL = 'GET_PO_DETAIL';
export const GET_PO_DETAIL_SUCCESS = 'GET_PO_DETAIL_SUCCESS';
export const GET_PO_SUCCESS = 'GET_PO_SUCCESS';
export const CHANGE_PO_STT = 'CHANGE_PO_STT';
export const DELETE_PO = 'DELETE_PO';
export const CREATE_PO = 'CREATE_PO';
export const UPDATE_PO = 'UPDATE_PO';

export const PO_REFUND_CREATE = 'PO/CREATE_REFUND';
export const PO_REFUND_CREATE_SUCCESS = 'PO/CREATE_REFUND_SUCCESS';
export const PO_REFUND_GET_LIST = 'PO/REFUND_GET_LIST';
export const PO_REFUND_GET_LIST_SUCCESS = 'PO/REFUND_GET_LIST_SUCCESS';
export const PO_REFUND_CHANGE_STT = 'PO/REFUND_CHANGE_STT';
export const PO_REFUND_CHANGE_STT_SUCCESS = 'PO/REFUND_CHANGE_STT_SUCCESS';
export const PO_REFUND_CHANGE_STATE = 'PO/REFUND_CHANGE_STATE';

export const SET_STATE_PO = 'SET_STATE_PO';
export const PO_UPDATE_CARRIER = 'PO_UPDATE_CARRIER';
export const PO_UPDATE_PACKING = 'PO_UPDATE_PACKING';
export const PO_UPDATE_TRACKING_NUMBER = 'PO_UPDATE_TRACKING_NUMBER';
export const PO_CHECK_STOCK = 'PO_CHECK_STOCK';
export const PO_CHECK_STOCK_COMPLETE = 'PO_CHECK_STOCK_COMPLETE';
export const PO_SET_COMPLETED = 'PO_SET_COMPLETED';
export const PO_CONFIRM_STATUS = 'PO_CONFIRM_STATUS';
export const PO_CONFIRM_DELIVERING = 'PO_CONFIRM_DELIVERING';
export const PO_CONFIRM_DELIVERED = 'PO_CONFIRM_DELIVERED';
export const PO_UPDATE_SHIPPING_ADDRESS = 'PO_UPDATE_SHIPPING_ADDRESS';
export const PO_APPLY_BRAND = 'PO_APPLY_BRAND';
export const PO_APPLY_BRAND_SUCCESS = 'PO_APPLY_BRAND_SUCCESS';
export const PO_SET_CANCEL = 'PO/SET_CANCEL';


export const PO_TRANSFER_CREATE = 'PO/TRANSFER_CREATE';
export const PO_TRANSFER_CREATE_SUCCESS = 'PO/TRANSFER_CREATE_SUCCESS';
;
export const GET_PO_PAYMENT = 'GET_PO_PAYMENT';
export const GET_PO_PAYMENT_SUCCESS = 'GET_PO_PAYMENT_SUCCESS';
export const CREATE_PO_PAYMENT = 'CREATE_PO_PAYMENT';

export const GET_WAREHOUSE = 'GET_WAREHOUSE';
export const GET_WAREHOUSE_SUCCESS = 'GET_WAREHOUSE_SUCCESS';
export const DELETE_WAREHOUSE = 'DELETE_WAREHOUSE';
export const DELETE_WAREHOUSE_SUCCESS = 'DELETE_WAREHOUSE_SUCCESS';
export const UPDATE_WAREHOUSE = 'UPDATE_WAREHOUSE';
export const UPDATE_WAREHOUSE_SUCCESS = 'UPDATE_WAREHOUSE_SUCCESS';
export const CREATE_WAREHOUSE = 'CREATE_WAREHOUSE';
export const CREATE_WAREHOUSE_SUCCESS = 'CREATE_WAREHOUSE_SUCCESS';
export const GET_WAREHOUSE_REPORT = 'GET_WAREHOUSE_REPORT';
export const GET_WAREHOUSE_REPORT_SUCCESS = 'GET_WAREHOUSE_REPORT_SUCCESS';


export const GET_CUSTOMER = 'GET_CUSTOMER';
export const GET_CUSTOMER_SUCCESS = 'GET_CUSTOMER_SUCCESS';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS';
export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS';

export const GET_BRAND = 'GET_BRAND';
export const GET_BRAND_SUCCESS = 'GET_BRAND_SUCCESS';
export const CREATE_BRAND = 'CREATE_BRAND';
export const CREATE_BRAND_SUCCESS = 'CREATE_BRAND_SUCCESS';
export const UPDATE_BRAND = 'UPDATE_BRAND';
export const UPDATE_BRAND_SUCCESS = 'UPDATE_BRAND_SUCCESS';
export const DELETE_BRAND = 'DELETE_BRAND';
export const DELETE_BRAND_SUCCESS = 'DELETE_BRAND_SUCCESS';

export const APPLY_BRAND_ORDER = 'APPLY_BRAND_ORDER';
export const APPLY_BRAND_ORDER_SUCCESS = 'APPLY_BRAND_ORDER_SUCCESS';

export const SET_STATE_ORDER = 'SET_STATE_ORDER';
export const GET_ORDER_LIST = 'GET_ORDER_LIST';
export const GET_ORDER_LIST_SUCCESS = 'GET_ORDER_LIST_SUCCESS';
export const GET_ORDER_DETAIL = 'GET_ORDER_DETAIL';
export const GET_ORDER_DETAIL_SUCCESS = 'GET_ORDER_DETAIL_SUCCESS';

export const GET_ORDER_TRANSACTION_LIST = 'GET_OT_LIST';
export const GET_OT_LIST_BY_ORDER = 'GET_OT_LIST_BY_ORDER';
export const GET_ORDER_TRANSACTION_LIST_SUCCESS = 'GET_OT_LIST_SUCCESS';
export const CREATE_ORDER_TRANSACTION = 'CREATE_OT';
export const CREATE_ORDER_TRANSACTION_SUCCESS = 'CREATE_OT_SUCCESS';
export const UPDATE_ORDER_TRANSACTION = 'UPDATE_OT';
export const UPDATE_ORDER_TRANSACTION_SUCCESS = 'UPDATE_OT_SUCCESS';
export const DELETE_ORDER_TRANSACTION = 'DELETE_OT';
export const DELETE_ORDER_TRANSACTION_SUCCESS = 'DELETE_OT_SUCCESS';
export const CHANGE_STATUS_ORDER_TRANSACTION_SUCCESS = 'CHANGE_STATUS_OT_SUCCESS';

export const OT_GET_RELATIONS = 'OT/GET_RELATIONS';
export const OT_GET_RELATIONS_SUCCESS = 'OT/GET_RELATIONS_SUCCESS';

export const GET_VENDOR = 'GET_VENDOR';
export const GET_VENDOR_SUCCESS = 'GET_VENDOR_SUCCESS';
export const DELETE_VENDOR = 'DELETE_VENDOR';
export const DELETE_VENDOR_SUCCESS = 'DELETE_VENDOR_SUCCESS';
export const UPDATE_VENDOR = 'UPDATE_VENDOR';
export const UPDATE_VENDOR_SUCCESS = 'UPDATE_VENDOR_SUCCESS';
export const CREATE_VENDOR = 'CREATE_VENDOR';
export const CREATE_VENDOR_SUCCESS = 'CREATE_VENDOR_SUCCESS';


export const GET_MANUFACTURE = 'GET_MANUFACTURE';
export const GET_MANUFACTURE_SUCCESS = 'GET_MANUFACTURE_SUCCESS';
export const DELETE_MANUFACTURE = 'DELETE_MANUFACTURE';
export const DELETE_MANUFACTURE_SUCCESS = 'DELETE_MANUFACTURE_SUCCESS';
export const UPDATE_MANUFACTURE = 'UPDATE_MANUFACTURE';
export const UPDATE_MANUFACTURE_SUCCESS = 'UPDATE_MANUFACTURE_SUCCESS';
export const CREATE_MANUFACTURE = 'CREATE_MANUFACTURE';
export const CREATE_MANUFACTURE_SUCCESS = 'CREATE_MANUFACTURE_SUCCESS';

export const GET_WAREHOUSE_PRODUCT = 'GET_WAREHOUSE_PRODUCT';
export const GET_WAREHOUSE_PRODUCT_SUCCESS = 'GET_WAREHOUSE_PRODUCT_SUCCESS';
export const GET_WAREHOUSE_VARIANT = 'GET_WAREHOUSE_VARIANT';
export const GET_WAREHOUSE_VARIANT_SUCCESS = 'GET_WAREHOUSE_VARIANT_SUCCESS';
export const GET_WAREHOUSE_TRANS = 'GET_WAREHOUSE_TRANS';
export const GET_WAREHOUSE_TRANS_SUCCESS = 'GET_WAREHOUSE_TRANS_SUCCESS';

export const WAREHOUSE_SET_DEFAULT = 'WAREHOUSE/SET_DEFAULT';
export const WAREHOUSE_SET_DEFAULT_SUCCESS = 'WAREHOUSE/SET_DEFAULT_SUCCESS';
export const WAREHOUSE_SET_STATE = 'WAREHOUSE/SET_STATE';

export const TAG_SET_STT = 'TAG_SET_STT';
export const TAG_GET_LIST = 'TAG_GET_LIST';
export const TAG_GET_LIST_SUCCESS = 'TAG_GET_LIST_SUCCESS';
export const TAG_CREATE = 'TAG_CREATE';
export const TAG_CREATE_SUCCESS = 'TAG_CREATE_SUCCESS';
export const TAG_UPDATE = 'TAG_UPDATE';
export const TAG_UPDATE_SUCCESS = 'TAG_UPDATE_SUCCESS';
export const TAG_DELETE = 'TAG_DELETE';
export const TAG_DELETE_SUCCESS = 'TAG_DELETE_SUCCESS';

export const CARRIER_SET_STT = 'CARRIER/SET_STT';
export const CARRIER_GET_LIST = 'CARRIER/GET_LIST';
export const CARRIER_GET_LIST_SUCCESS = 'CARRIER/GET_LIST_SUCCESS';
export const CARRIER_CREATE = 'CARRIER/CREATE';
export const CARRIER_CREATE_SUCCESS = 'CARRIER/CREATE_SUCCESS';
export const CARRIER_UPDATE = 'CARRIER/UPDATE';
export const CARRIER_UPDATE_SUCCESS = 'CARRIER/UPDATE_SUCCESS';
export const CARRIER_DELETE = 'CARRIER/DELETE';
export const CARRIER_DELETE_SUCCESS = 'CARRIER/DELETE_SUCCESS';

export const OT_COD_CONFIRM = 'OT/COD_CONFIRM';
export const OT_COD_CONFIRM_SUCCESS = 'OT/COD_CONFIRM_SUCCESS';
export const OT_DEPOSIT_CONFIRM = 'OT/DEPOSIT_CONFIRM';
export const OT_DEPOSIT_CONFIRM_SUCCESS = 'OT/DEPOSIT_CONFIRM_SUCCESS';
export const OT_SET_CANCEL = 'OT/SET_CANCEL';
export const OT_SET_CANCEL_SUCCESS = 'OT/SET_CANCEL_SUCCESS';
export const OT_SET_NOTE = 'OT/SET_NOTE';
export const OT_SET_NOTE_SUCCESS = 'OT/SET_NOTE_SUCCESS';
export const OT_SET_COMPLETE_SUCCESS = 'OT/SET_COMPLETE_SUCCESS';
export const OT_SET_COMPLETE = 'OT/SET_COMPLETE';

export const ADJ_CHANGE_STT = 'ADJUSTMENT/CHANGE_STT';
export const ADJ_GET_LIST = 'ADJUSTMENT/GET_LIST';
export const ADJ_GET_LIST_SUCCESS = 'ADJUSTMENT/GET_LIST_SUCCESS';
export const ADJ_CREATE = 'ADJUSTMENT/CREATE';
export const ADJ_CREATE_SUCCESS = 'ADJUSTMENT/CREATE_SUCCESS';
export const ADJ_UPDATE = 'ADJUSTMENT/UPDATE';
export const ADJ_UPDATE_SUCCESS = 'ADJUSTMENT/UPDATE_SUCCESS';
export const ADJ_CANCEL = 'ADJUSTMENT/CANCEL';
export const ADJ_CANCEL_SUCCESS = 'ADJUSTMENT/CANCEL_SUCCESS';
export const ADJ_CONFIRM = 'ADJUSTMENT/CONFIRM';
export const ADJ_CONFIRM_SUCCESS = 'ADJUSTMENT/CONFIRM_SUCCESS';
